# Generated by Django 5.1.3 on 2024-12-01 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('actor', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('number', models.IntegerField()),
                ('con', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.conversation')),
            ],
        ),
        migrations.DeleteModel(
            name='QuestionAnswer',
        ),
    ]
