# Generated by Django 5.1.3 on 2025-01-29 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_multiple_document_multiple_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multiple',
            name='files',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
