# Generated by Django 5.1.3 on 2025-01-31 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_alter_multiple_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='multiple',
            name='document',
        ),
    ]
